language: python

python: "3.8"

# don't clone more than necessary
git:
  depth: 1

# Install any dependencies
install:
  - pip install -r requirements.txt

# script to run tests. Script can have many commands, one per line.
script:
#  - python -m unittest discover -p "*_test.py"
  - coverage run -m unittest discover -p "*_test.py"

after_success:
  - codecov